#!/bin/sh

rsync -rav --delete \
	--exclude '.*' \
	--exclude node_modules \
	--exclude 'cached/*' \
	. 'europa:~/travel-price-map-rest/'

ssh europa "\
cd ~/travel-price-map-rest
npm i
npm update
forever-service delete travel-price-map-rest
forever-service install travel-price-map-rest --start -s index.js"
