#!/bin/sh

rsync -rav --delete \
	--exclude '.*' \
	--exclude node_modules \
	--exclude 'cached/*' \
	. 'enceladus:~/travel-price-map-rest/'

ssh enceladus "\
cd ~/travel-price-map-rest
npm i
npm update
forever stop travel-price-map-rest
forever start -a --uid travel-price-map-rest index.js"
